
// This file was auto-generated by ML.NET Model Builder. 

using Leasing1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
Leasing1.ModelInput sampleData = new Leasing1.ModelInput()
{
    Area = @"Mission Valley",
    Floor_Plan = @"1 bedroom",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Rent with predicted Rent from sample data...\n\n");


Console.WriteLine($"Area: {@"Mission Valley"}");
Console.WriteLine($"Floor_Plan: {@"1 bedroom"}");
Console.WriteLine($"Rent: {2600F}");


// Make a single prediction on the sample data and print results
var predictionResult = Leasing1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Rent: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

