// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLTest1l_WebApi
{
    public partial class Leasing1
    {
        /// <summary>
        /// model input class for Leasing1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Area")]
            public string Area { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Floor Plan")]
            public string Floor_Plan { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Rent")]
            public float Rent { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Leasing1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Area")]
            public string Area { get; set; }

            [ColumnName(@"Floor Plan")]
            public string Floor_Plan { get; set; }

            [ColumnName(@"Rent")]
            public float Rent { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Leasing1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
