// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using Microsoft.ML.Data;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MLTest1l_WebApi.Models;
using MLTest1l_WebApi;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<MLTest1l.ModelInput, MLTest1l.ModelOutput>()
    .FromFile("MLTest1l.mlnet");
builder.Services.AddPredictionEnginePool<Leasing1.ModelInput, Leasing1.ModelOutput>()
    .FromFile("Leasing1.mlnet");

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddControllers();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

//if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    });
}

// Define prediction route & handler
//app.MapPost("/predict",
//    async (PredictionEnginePool<MLTest1l.ModelInput, MLTest1l.ModelOutput> predictionEnginePool, MLTest1l.ModelInput input) =>
//    {
//        MLTest1l.ModelInput sampleData = new MLTest1l.ModelInput()
//        {
//            Rate_code = 1F,
//            Trip_distance = 1.5F,
//        };

//        MLTest1l.ModelOutput response = predictionEnginePool.Predict(input);
//        ApiResults res = new ApiResults();
//        res.results = new List<Result>();
//        res.results.Add(new Result() { toolCallId = "", result = response.Score.ToString() });
//        await Task.FromResult(res);
//    });
app.UseRouting();
app.UseCors("AllowAll");
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});

// Run app
app.Run();
