
// This file was auto-generated by ML.NET Model Builder. 

using MLTest1l_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLTest1l.ModelInput sampleData = new MLTest1l.ModelInput()
{
    Rate_code = 1F,
    Trip_distance = 1.5F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Fare_amount with predicted Fare_amount from sample data...\n\n");


Console.WriteLine($"Rate_code: {1F}");
Console.WriteLine($"Trip_distance: {1.5F}");
Console.WriteLine($"Fare_amount: {8F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLTest1l.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Fare_amount: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

